Ext.namespace('Dmpc.view.templates');
Dmpc.view.templates.TalkDetail = new Ext.XTemplate(
    '<tpl for=".">',
        '<div class="talkDetail {conference}">',
            '<header class="clearfix">',
                '<h2 class="title"><span>',
                    '{title}',
                '</span></h2>',
                '<a class="selectedButton {[ this.getIsSelectedClass(values.title, values.day) ]}" id="selectedBtn" href="#{id}" onclick="return false;">&nbsp;</a>',
            '</header>',
            '<div class="talkInfo">',
                '<p class="sessiontime">{time} - {time_end} ({talk_type})</p>',
                '<tpl if="talk_level"><span class="sessionicon1 {talk_level}">&nbsp;</span></tpl>',
                '<tpl if="talk_orientation"><span class="sessionicon2 {talk_orientation}">&nbsp;</span></tpl>',
                '<p>{description}</p>',
            '</div>',
            '<tpl for="speakers">',
                '<header class="clearfix">',
                    '<h2 class="title">',
                        '{name}',
                    '</h2>',
                '</header>',
                '<div class="talkInfo">',
                    '<img src="resources/images/speakers/{photo.filename}" class="speakerImg">',
                    '<p>{bio}</p>',
                '</div>',
            '</tpl>',
        '</div>',
     '</tpl>',
     Ext.create('Dmpc.view.HelperFunctions')
);